name: Enforce Branch Name Rules

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        env:
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          echo "Source branch: $BRANCH_NAME"
          if [[ "$BRANCH_NAME" != feature/* && \
                "$BRANCH_NAME" != bugfix/* && \
                "$BRANCH_NAME" != release/* && \
                "$BRANCH_NAME" != dependabot/* && \
                "$BRANCH_NAME" != latest && \
                "$BRANCH_NAME" != fe/* && \
                "$BRANCH_NAME" != be/* && \
                "$BRANCH_NAME" != e2e/* && \
                "$BRANCH_NAME" != test/* && \
                "$BRANCH_NAME" != docs/* && \
                "$BRANCH_NAME" != ric/* ]]; then
            echo "‚ùå Pull requests to 'main' are only allowed from 'feature/**', 'bugfix/**', 'release/**', 'dependabot/**', 'latest', 'test/**', 'docs/**', or 'ric/**' branches."
            exit 1
          fi
