name: ðŸ“– Release (stage)

on:
  push:
    branches:
      - "release/**"

jobs:
  tests:
    name: Release stage tests
    uses: ./.github/workflows/tests.yml
    secrets: inherit
    with:
      short_rte_list: false
      pre_release: true

  builds:
    name: Release stage builds
    uses: ./.github/workflows/build.yml
    needs: tests
    secrets: inherit
    with:
      environment: "staging"
      target: "all"

  aws:
    uses: ./.github/workflows/aws-upload-dev.yml
    needs: [builds]
    secrets: inherit
    if: always()
    with:
      pre-release: true

  e2e-docker-tests-smoke:
    name: "E2E: Smoke (Docker)"
    needs: builds
    uses: ./.github/workflows/tests-e2e-docker-smoke.yml
    secrets: inherit
    with:
      debug: ${{ inputs.debug || false }}

  e2e-docker-tests-critical-path:
    name: "E2E: Critical Path (Docker)"
    needs: builds
    uses: ./.github/workflows/tests-e2e-docker-critical-path.yml
    secrets: inherit
    with:
      debug: ${{ inputs.debug || false }}

  e2e-docker-tests-regression:
    name: "E2E: Regression (Docker)"
    needs: builds
    uses: ./.github/workflows/tests-e2e-docker-regression.yml
    secrets: inherit
    with:
      debug: ${{ inputs.debug || false }}

  e2e-appimage-tests:
    needs: builds
    uses: ./.github/workflows/tests-e2e-appimage.yml
    secrets: inherit

  # Remove artifacts from github actions
  remove-artifacts:
    name: Remove artifacts
    needs:
      [
        aws,
        e2e-docker-tests-smoke,
        e2e-docker-tests-critical-path,
        e2e-docker-tests-regression,
        e2e-appimage-tests,
      ]
    if: always()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Remove all artifacts
        uses: ./.github/actions/remove-artifacts # Remove artifacts from github actions
